### ISSUE TITLE
邮件主题中可否增加魔法变量

### ISSUE THREAD

**Issue by SkyrimKO** [Me-turing/SendMailTools#1]
您好，是否可以实现邮件主题中增加魔法变量，主要是想在主题中添加附件文件名。
使用中发现[README.md](https://github.com/Me-turing/SendMailTools/blob/main/README.md)文件中描述的邮件内容中魔法变量，表示时间的 {data} 不行，换成 {date} 就可以了。

**Comment by SEVENTEEN-TAN** [comment]
感谢指出 手误手误
